spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alipay
    username: root
    password: root
  redis:
    host: 43.143.139.24
    password: songyang.top@@##$$
    jedis:
      pool:
        enabled: true
logging:
  level:
    root: info