spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empdb
    username: root
    password: root
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filters: stat
logging:
  level:
    root: info
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
jwt:
  name: 宋洋111
#  file:
#    name: C:\Users\Mr.Song\Desktop\a.txt